services:
  mongodb:
    image: mongo:latest
    container_name: benchmark-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=benchmark
    volumes:
      - mongodb_data:/data/db
    networks:
      - benchmark-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/benchmark --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    container_name: benchmark-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=benchmark
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - benchmark-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:
  postgres_data:

networks:
  benchmark-network:
    driver: bridge 